apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "name" . }}
webhooks:
- name: mutation.service.dns.extensions.gardener.cloud
  rules:
  - apiGroups:
    - "core.gardener.cloud"
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - shoots
  failurePolicy: Fail
  objectSelector:
    {{- toYaml (default (dict) .Values.global.webhookConfig.objectSelector) | nindent 4 }}
  namespaceSelector: {}
  sideEffects: None
  admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    {{- if .Values.global.virtualGarden.enabled }}
    url: {{ printf "https://%s.%s/webhooks/mutate" (include "name" .) (.Release.Namespace) }}
    {{- else }}
    service:
      namespace: {{ .Release.Namespace }}
      name: {{ include "name" . }}
      path: /webhooks/mutate
    {{- end }}
    caBundle: {{ required ".Values.global.webhookConfig.caBundle is required" .Values.global.webhookConfig.caBundle | b64enc }}
